#Single ecs test template
heat_template_version: 2015-10-15

description: Advanced template to a single ecs named singleecs

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance.
    default: Standard_CentOS_7_latest
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: s1.medium
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance.
    default: nor
  private_network:
    type: string
    label: External Network name or ID
    description: Name of the network which we place the ecs
    default: 24e8b384-56c6-4a97-bf1d-40e11de068a0

resources:
  server_init:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /tmp/test
          content: "Hello OTC"
        groups:
          - ugroup
        users:
          - default
          - name: demo
            gecos: demostration user
            primary_group: demo
            groups: users
            sudo: ALL=(ALL) NOPASSWD:ALL
            home: /home/demo
            plain_text_passwd: 'demo4otc' 
            ssh_redirect_user: true

  otc-server:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key }
      security_groups: ["default"]
      availability_zone: eu-de-02
      networks:
        - network: { get_param: private_network }
      user_data:
        get_resource: server_init
      user_data_format: RAW

outputs:
  id:
    description: name of the single ecs.
    value: { get_attr: [otc-server, name] }
  ip:
    description: The ips address of the instance .
    value: { get_attr: [otc-server, first_address] }
  cf:
    description: cloud config detail
    value: { get attr: [server_init, cloud_config] }
